### ISSUE TITLE
29/06/2018: 3º Meetup do TC em Porto Alegre - Agora vai!

### ISSUE THREAD

**Issue by narukaioh** [danicat/eventos-ti#4]
Local: Porto Alegre-RS
URL: https://www.meetup.com/Training-Center-RS/events/250418877/

**Comment by danicat** [comment]
Tinha faltado associar o projeto [no lado direito da tela - clica em Projects]

**Comment by narukaioh** [comment]
não consigo associar um projeto

**Comment by danicat** [comment]
Sem crise, já adicionei... mas preciso descobrir como automatizar isso.
